export const CONTRACT_ENGINE_ERROR_CODES = Object.freeze({
  CONTRACT_REQUIRED: "PCE-CONTRACT-001",
  MANIFEST_REQUIRED: "PCE-MANIFEST-001",
  RUNTIME_UNSUPPORTED: "PCE-RUNTIME-001",
  TARGET_UNSUPPORTED: "PCE-TARGET-001",
  SOURCE_UNSUPPORTED: "PCE-SOURCE-001",
  ACTION_REQUIRED: "PCE-ACTION-001",
  RUNTIME_NOT_IN_MANIFEST: "PCE-RUNTIME-002",
  WORKFLOW_AUTHORITY_VIOLATION: "PCE-AUTH-001",
  CAPABILITY_RUNTIME_MISMATCH: "PCE-CAPABILITY-001",
  CONTRACT_SCHEMA_INVALID: "PCE-CONTRACT-002",
  MISSING_CONTRACT_SECTION: "PCE-CONTRACT-003",
});
