export const POLICY_ENGINE_ERROR_CODES = {
  CONTRACT_REQUIRED: "PPE-CONTRACT-001",
  CONTRACT_INVALID: "PPE-CONTRACT-002",
  RUNTIME_CONTEXT_UNRESOLVED: "PPE-RUNTIME-001",
  TARGET_CONTEXT_UNRESOLVED: "PPE-TARGET-001",
};
