# PairSlash git-status watcher
# Monitors working tree for changes and auto-generates a commit message
# into .git_commit_msg based on current git status.
#
# Usage: pwsh -File scripts/git-commit-msg-watcher.ps1 [<repo-root>]

param(
    [string]$RepoRoot = $PSScriptRoot ? (Split-Path $PSScriptRoot -Parent) : (Get-Location).Path
)

$commitMsgFile = Join-Path $RepoRoot ".git_commit_msg"
$debounceMs    = 3000   # wait this long after last change before regenerating
$global:lastEventTime = [datetime]::MinValue
$indexLockPath = Join-Path $RepoRoot ".git\index.lock"

# ── helpers ───────────────────────────────────────────────────────────────────

function Get-ConventionalType([string[]]$paths) {
    $hasSkill  = $paths | Where-Object { $_ -match 'skills/' }
    $hasSpec   = $paths | Where-Object { $_ -match 'specs/' }
    $hasSchema = $paths | Where-Object { $_ -match 'schemas/' }
    $hasMemory = $paths | Where-Object { $_ -match '\.pairslash/' }
    $hasCompat = $paths | Where-Object { $_ -match 'compatibility/' -or $_ -match 'checklists/' }
    $hasDocs   = $paths | Where-Object { $_ -match '^docs/' -or ($_ -match '\.md$' -and $_ -notmatch 'skills/') }
    $hasChore  = $paths | Where-Object { $_ -match '\.gitignore|package\.json|\.github/copilot' }

    if ($hasSkill -or $hasSpec -or $hasSchema) { return "feat" }
    if ($hasMemory)  { return "feat" }
    if ($hasCompat)  { return "chore" }
    if ($hasDocs)    { return "docs" }
    if ($hasChore)   { return "chore" }
    return "chore"
}

function Build-CommitMessage {
    # Skip if another git operation is in progress (prevents index lock contention)
    if (Test-Path $indexLockPath) { return $null }

    Push-Location $RepoRoot

    $rawStatus = git --no-optional-locks --no-pager status --short 2>&1
    if ($LASTEXITCODE -ne 0 -or -not $rawStatus) {
        Pop-Location
        return $null
    }

    $added    = @()
    $modified = @()
    $deleted  = @()
    $renamed  = @()
    $allPaths = @()

    foreach ($line in $rawStatus) {
        if ($line -match '^[?][?]\s+(.+)$') { continue }   # untracked — skip
        $xy   = $line.Substring(0, 2).Trim()
        $rest = $line.Substring(3).Trim()

        # arrow means rename: "old -> new"
        if ($rest -match ' -> (.+)$') { $rest = $Matches[1] }
        $rest = $rest.Trim('"')
        $allPaths += $rest

        switch -Regex ($xy) {
            'A' { $added    += $rest }
            'M' { $modified += $rest }
            'D' { $deleted  += $rest }
            'R' { $renamed  += $rest }
        }
    }

    Pop-Location

    if ($allPaths.Count -eq 0) { return $null }

    $type = Get-ConventionalType $allPaths

    # Scope = most common top-level directory (strip leading dot)
    $dirs  = $allPaths | ForEach-Object { ($_ -split '[/\\]')[0] } | Group-Object | Sort-Object Count -Descending
    $scope = if ($dirs) { $dirs[0].Name -replace '^\.','' } else { "" }

    # Subject line parts
    $parts = @()
    if ($added.Count -gt 0) {
        $label = if ($added.Count -eq 1) { Split-Path $added[0] -Leaf } else { "$($added.Count) files" }
        $parts += "add $label"
    }
    if ($modified.Count -gt 0) {
        $label = if ($modified.Count -eq 1) { Split-Path $modified[0] -Leaf } else { "update $($modified.Count) files" }
        $parts += $label
    }
    if ($deleted.Count -gt 0) {
        $label = if ($deleted.Count -eq 1) { Split-Path $deleted[0] -Leaf } else { "remove $($deleted.Count) files" }
        $parts += $label
    }
    if ($renamed.Count -gt 0) {
        $parts += "rename $($renamed.Count) files"
    }

    $subject = $parts -join ", "
    $header  = if ($scope) { "${type}(${scope}): ${subject}" } else { "${type}: ${subject}" }

    # Body: list all changed paths
    $bodyLines = @("Changed files:")
    foreach ($p in ($allPaths | Sort-Object)) { $bodyLines += "  - $p" }

    $timestamp = Get-Date -Format "yyyy-MM-ddTHH:mm:sszzz"
    $msg = @(
        $header,
        "",
        ($bodyLines -join "`n"),
        "",
        "# Auto-generated by git-commit-msg-watcher at $timestamp",
        "# Edit before committing."
    ) -join "`n"

    return $msg
}

function Write-CommitMsg {
    $msg = Build-CommitMessage
    if ($msg) {
        try {
            Set-Content -Path $commitMsgFile -Value $msg -Encoding UTF8 -ErrorAction Stop
            $short = ($msg -split "`n")[0]
            Write-Host "[$([datetime]::Now.ToString('HH:mm:ss'))] .git_commit_msg updated: $short"
        } catch {
            Write-Host "[$([datetime]::Now.ToString('HH:mm:ss'))] Skipped write (file in use)"
        }
    }
}

# ── initial write ─────────────────────────────────────────────────────────────

if (-not (Test-Path $commitMsgFile)) {
    New-Item -Path $commitMsgFile -ItemType File -Force | Out-Null
}
Write-CommitMsg

# ── filesystem watcher ────────────────────────────────────────────────────────

$watcher = New-Object System.IO.FileSystemWatcher
$watcher.Path                  = $RepoRoot
$watcher.IncludeSubdirectories = $true
$watcher.EnableRaisingEvents   = $true
$watcher.NotifyFilter          = [System.IO.NotifyFilters]::FileName `
                               -bor [System.IO.NotifyFilters]::LastWrite `
                               -bor [System.IO.NotifyFilters]::DirectoryName

$ignorePattern = [regex]'(\\|/)\.git(\\|/)|\.git_commit_msg$'

$debounceAction = {
    $path = $Event.SourceEventArgs.FullPath
    if ($path -match $ignorePattern) { return }
    $global:lastEventTime = [datetime]::Now
}

Register-ObjectEvent $watcher Changed -Action $debounceAction | Out-Null
Register-ObjectEvent $watcher Created -Action $debounceAction | Out-Null
Register-ObjectEvent $watcher Deleted -Action $debounceAction | Out-Null
Register-ObjectEvent $watcher Renamed -Action $debounceAction | Out-Null

Write-Host "Watching $RepoRoot for changes... (Ctrl+C to stop)"
Write-Host "Writing commit messages to: $commitMsgFile"

try {
    while ($true) {
        Start-Sleep -Milliseconds 500
        $now = [datetime]::Now
        if ($global:lastEventTime -ne [datetime]::MinValue) {
            $msSinceLast = ($now - $global:lastEventTime).TotalMilliseconds
            if ($msSinceLast -ge $debounceMs) {
                $global:lastEventTime = [datetime]::MinValue
                Write-CommitMsg
            }
        }
    }
} finally {
    $watcher.EnableRaisingEvents = $false
    $watcher.Dispose()
    Get-EventSubscriber | Unregister-Event
}
